apiVersion: v1
kind: Service
metadata:
  name: orders-returns-srv
spec:
  type: NodePort
  selector:
    app: orders-returns-service
  ports:
    - name: orders-returns-service
      protocol: TCP
      port: 3006
      targetPort: 3006
