apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: products:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: products-clusterip-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3006
      targetPort: 3006
