apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3006
      targetPort: 3006
